
version: "3.8"

services:
  app:
    build: .
    container_name: wid-user
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
  
  mongo:
    image: mongo:latest
    container_name: wid-mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  haproxy:
    image: haproxy:latest
    container_name: haproxy-loadbalancer
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - app
  
volumes:
  mongo-data:
